config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :adds
  resources :blogs
  root to:"adds#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/add.rb
class Add < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/controllers/adds_controller.rb
class AddsController < ApplicationController
  before_action :set_add, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create edit update destroy new ]

  # GET /adds or /adds.json
  def index
    @adds = Add.all
  end

  # GET /adds/1 or /adds/1.json
  def show
  end

  # GET /adds/new
  def new
    @add = Add.new
  end

  # GET /adds/1/edit
  def edit
  end

  # POST /adds or /adds.json
  def create
    @add = Add.new(add_params)

    respond_to do |format|
      if @add.save
        format.html { redirect_to @add, notice: "Add was successfully created." }
        format.json { render :show, status: :created, location: @add }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @add.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adds/1 or /adds/1.json
  def update
    respond_to do |format|
      if @add.update(add_params)
        format.html { redirect_to @add, notice: "Add was successfully updated." }
        format.json { render :show, status: :ok, location: @add }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @add.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adds/1 or /adds/1.json
  def destroy
    @add.destroy
    respond_to do |format|
      format.html { redirect_to adds_url, notice: "Add was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add
      @add = Add.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_params
      params.require(:add).permit(:title, :description, :is_published, :images)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.fetch(:blog, {})
    end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/adds/_form.html.erb
<%= form_with(model: add) do |form| %>
  <% if add.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add.errors.count, "error") %> prohibited this add from being saved:</h2>

      <ul>
        <% add.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :is_published %>
    <%= form.check_box :is_published %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adds/edit.html.erb
<h1>Editing Add</h1>

<%= render 'form', add: @add %>

<%= link_to 'Show', @add %> |
<%= link_to 'Back', adds_path %>

app/views/adds/index.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Add Advertisments</h1>
    <p class="lead">This  is a web Application to add Advertisment . Feel Free to add any Advertisment of your choice 😋😋😋</p>
  </div>
</div>

  <div class="container">
  <div class="row">

  <% @adds.each do |add| %>
    <% if add.is_published %>
    <div class="col col-md-3" style="margin:0.7em;">
    <div class="card" style="width: 18rem;">
    <img src=<%= add.images %> class="card-img-top" alt="abab">
    <div class="card-body">
      <h5 class="card-title"><%= add.title %></h5>
      <p class="card-text"><%= add.description %></p>
      <button class="btn btn-primary" style="text-decoration: none;"><%= link_to  'Show', add %></button>
    </div>
  </div>
  </div>
    <% end %>
    

      
 
  <% end %>
    
  </div>
</div>
  
   
 
<br>

app/views/adds/new.html.erb
<h1>New Add</h1>

<%= render 'form', add: @add %>

<%= link_to 'Back', adds_path %>

app/views/adds/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container container-fluid">

<div class="row">
<% if user_signed_in? %>
<div class="col col-md-3" style="margin:1em">

<div class="card" style="width: 18rem; margin:1em">
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><button class="btn btn-outline-secondary"><%= link_to 'Edit', edit_add_path(@add) %> </button></li>
    <li class="list-group-item"><button class="btn btn-outline-info"><%= link_to 'Back', adds_path %></button></li>
    <li class="list-group-item"><%= link_to 'Destroy', @add, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  </ul>
</div>

</div>
<% end %> 

<div class="col col-md-8">
<img src=<%= @add.images %> class="img-fluid" alt="Responsive image">
<p>
  <h2><strong>Title:</strong></h2>
  <%= @add.title %>
</p>
<br/>
<p>
 <h2> <strong>Description:</strong></h2>
 <h6><%= @add.description %></h6>
</p>

<br/>
<p>
 <h2> <strong>Is published:</strong> </h2>
 <h6> <%= @add.is_published %><h6>
</p>
</div>
 



</div>


</div>




 |

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advertisment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand">Advertisment</a>
    <form class="d-flex">
    <button class="btn btn-outline-success my-2 my-sm-0"><a style="text-decoration: none;" href="admin/login">
    <%= link_to 'New Add', new_add_path %>
    </a></button>
   
    <% if user_signed_in? %>
    <p class="ml-1"> <%= current_user.email %> </p>
    <%= link_to'Signout',destroy_user_session_path,method: :delete %>
    
    <% end %>
    <% if !user_signed_in? %>
    <button class="btn btn-outline-info my-2 my-sm-0"><a style="text-decoration: none;" href="admin/sign_up">Register</a></button>
    <button class="btn btn-outline-success my-2 my-sm-0"><a style="text-decoration: none;" href="admin/login">Login</a></button>
    <% end %>
    
    </form>
  </div>
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
 
  <body>
  
    <%= yield %>
  </body>
</html>